// client-app/src/features/search/_components/course-card.tsx
import { BookOpen } from "lucide-react";
import { formatPrice } from "@/lib/format";
import { IconBadge } from "@/components/icon-badge";
import { Link } from "@tanstack/react-router";
import { CourseProgress } from "./course-progress";

interface CourseCardProps {
  id: string;
  title: string;
  imageUrl: string;
  chaptersLength: number;
  price: number;
  progress: number | null;
  category?: string;
}

export const CourseCard = ({ id, title, imageUrl, chaptersLength, price, progress, category }: CourseCardProps) => {
  return (
    <Link to="/courses/$courseId" params={{ courseId: id }}>
      <div className="group hover:shadow-sm transition overflow-hidden border rounded-lg p-3 h-full">
        <div className="relative w-full aspect-video rounded-md overflow-hidden">
          <img className="object-cover" alt={title} src={imageUrl} />
        </div>
        <div className="flex flex-col pt-2">
          <div className="text-ld md:text-base font-medium group-hover:text-sky-700 transition line-clamp-2">
            {title}
          </div>
          <p className="text-xs text-muted-foreground">{category}</p>
          <div className="my-3 flex items-center gap-x-2 text-xs md:text-xs">
            <div className="flex items-center gap-x-1 text-slate-500">
              <IconBadge size="small" icon={BookOpen} />
              <span>
                {chaptersLength} {chaptersLength === 1 ? "Chapter" : "Chapters"}
              </span>
            </div>
          </div>
          {progress !== null ? (
            <CourseProgress value={progress} size="sm" variant={progress === 100 ? "success" : "default"} />
          ) : (
            <p className="text-md md:text-sm font-medium text-slate-700">{formatPrice(price)}</p>
          )}
        </div>
      </div>
    </Link>
  );
};

// angular-client-app/src/app/shared/course-card.component.ts
import { Component, input } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatIconModule } from '@angular/material/icon';

@Component({
  selector: 'lms-course-card',
  imports: [MatCardModule, MatButtonModule, MatIconModule],
  template: `
    <div
      class="group hover:shadow-sm transition overflow-hidden border rounded-lg p-3 h-full"
    >
      <div class="relative w-full aspect-video rounded-md overflow-hidden">
        <img class="object-cover" alt="{{ title() }}" src="{{ imageUrl() }}" />
      </div>
      <div class="flex flex-col pt-2">
        <div
          class="text-ld md:text-base font-medium group-hover:text-sky-700 transition line-clamp-2"
        >
          {{ title() }}
        </div>
        <p class="text-xs text-muted-foreground">{{ category() }}</p>
        <div class="my-3 flex items-center gap-x-2 text-xs md:text-xs">
          <div class="flex items-center gap-x-1 text-slate-500">
            <mat-icon>library_books</mat-icon>
            <span> x chapters </span>
          </div>
        </div>
        <p class="text-md md:text-sm font-medium text-slate-700">price</p>
      </div>
    </div>
  `,
  styles: ``,
})
export class CourseCardComponent {
  title = input.required<string>();
  imageUrl = input<string>();
  category = input<string>();
}
