// client-app/src/features/search/_components/categories.tsx
import {
  FcEngineering,
  FcFilmReel,
  FcMultipleDevices,
  FcMusic,
  FcOldTimeCamera,
  FcSalesPerformance,
  FcSportsMode,
} from "react-icons/fc";
import { IconType } from "react-icons/lib";
import { Suspense } from "react";
import { Category } from "@/features/courses/types";
import { CategoryItem } from "./category-item";

interface CategoriesProps {
  items?: Category[];
}

const iconMap: Record<Category["name"], IconType> = {
  Music: FcMusic,
  Photography: FcOldTimeCamera,
  Fitness: FcSportsMode,
  Accounting: FcSalesPerformance,
  "Computer Science": FcMultipleDevices,
  Filming: FcFilmReel,
  Engineering: FcEngineering,
};

export const Categories = ({ items }: CategoriesProps) => {
  return (
    <div className="flex  items-center gap-x-2 overflow-x-auto pb-2">
      <Suspense>
        {items?.map((item) => (
          <CategoryItem key={item.id} label={item.name} icon={iconMap[item.name]} value={item.id} />
        ))}
      </Suspense>
    </div>
  );
};

// angular-client-app/src/app/search/ui/categories.component.ts
import { Component, input, output } from '@angular/core';
import { Category } from '../../shared/types';
import { CategoryItemComponent } from './category-item.component';

@Component({
  selector: 'lms-categories',
  imports: [CategoryItemComponent],
  template: `
    <div>
      @for(category of categories(); track category.id) {
      <a (click)="selectCategory.emit(category.id)">
        <lms-category-item
          [label]="category.name"
          [icon]="iconMap[category.name]"
          [selected]="category.isSelected"
        />
      </a>
      }
    </div>
  `,
  styles: ``,
})
export class CategoriesComponent {
  categories = input<Category[] & { isSelected: boolean }[]>();
  selectCategory = output<string>();

  iconMap: Record<Category['name'], string> = {
    Music: 'music_note',
    Photography: 'photo_camera',
    Fitness: 'directions_bike',
    Accounting: 'calculate',
    'Computer Science': 'devices',
    Filming: 'local_movies',
    Engineering: 'engineering',
  };
}
