// client-app/src/features/playback/_components/video-player.tsx
import { useConfettiStore } from "@/hooks/use-confetti-store";
import { useNavigate } from "@tanstack/react-router";
import { Lock } from "lucide-react";
import toast from "react-hot-toast";
import { useUpdateProgress } from "../api/use-update-progress";

interface VideoPlayerProps {
  url?: string | null | undefined;
  contentType?: string;
  courseId: string;
  chapterId?: string;
  nextChapterId?: string;
  title: string;
  isLocked: boolean;
  completeOnEnd: boolean;
}

export const VideoPlayer = ({
  chapterId,
  courseId,
  nextChapterId,
  url,
  contentType = "",
  isLocked,
  completeOnEnd,
}: VideoPlayerProps) => {
  //const [isReady, setIsReady] = useState(false);
  const confetti = useConfettiStore();
  const navigate = useNavigate();
  const { updateProgress } = useUpdateProgress();
  const onEnd = async () => {
    console.log("onEnd");
    if (completeOnEnd) {
      updateProgress({ courseId, chapterId: chapterId!, isCompleted: true })
        .then(() => {
          if (!nextChapterId) {
            confetti.onOpen();
          }
          toast.success("Progress updated");
        })
        .catch(() => {
          toast.error("Something went wrong");
        });
      if (nextChapterId) {
        navigate({ to: "/courses/$courseId/chapters/$chapterId", params: { courseId, chapterId: nextChapterId } });
      }
    }
  };

  if (!url) return null;

  return (
    <div className="relative aspect-video">
      {isLocked && (
        <div className="absolute inset-0 flex items-center justify-center bg-slate-800 flex-col gap-y-2 text-secondary">
          <Lock className="h-8 w-8" />
          <p className="text-sm">This chapter is locked</p>
        </div>
      )}
      {!isLocked && (
        <video controls key={url} className="w-full" onEnded={onEnd}>
          <source src={url} type={contentType} />
          <p>
            Your browser doesn't support HTML video. Here is a <a href={url}>link to the video</a>
            instead.
          </p>
        </video>
      )}
    </div>
  );
};

// angular-client-app/src/app/playback/ui/video-player.component.ts
import { Component, effect, ElementRef, input, viewChild } from '@angular/core';
import { MatIconModule } from '@angular/material/icon';

@Component({
  selector: 'lms-video-player',
  imports: [MatIconModule],
  template: `
    <div class="relative aspect-video">
      @if(isLocked()){
      <div
        class="absolute inset-0 flex items-center justify-center bg-slate-800 flex-col gap-y-2 text-secondary"
      >
        <mat-icon class="h-8 w-8 icon-white">lock</mat-icon>
        <p class="text-sm text-white">This chapter is locked</p>
      </div>
      } @else if(url()) {
      <video #videoPlayer controls class="w-full">
        <source [src]="url()" [type]="contentType()" />
        <p>
          Your browser doesn't support HTML video. Here is a
          <a [href]="url()">link to the video</a>
          instead.
        </p>
      </video>
      }
    </div>
  `,
  styles: ``,
})
export class VideoPlayerComponent {
  url = input<string | undefined>('');
  contentType = input<string | undefined>('');
  isLocked = input<boolean>(false);

  videoPlayer = viewChild<ElementRef<HTMLVideoElement>>('videoPlayer');

  constructor() {
    effect(() => {
      const url = this.url();
      const videoEl = this.videoPlayer()?.nativeElement;
      if (url && videoEl && typeof videoEl.load === 'function') {
        videoEl.load();
      }
    });
  }
}
